Added Interpolation
StudyUnity-Organization/StudyUnityMathLib pull request #4
Opened 2023-11-25 17:01 UTC by COBRA445

2023-11-26 19:24 UTC, Gr871 commented on Assets/Scripts/CustomMath/Vector3D.cs
> +        public enum coordRotationAroundDirection { X, Y, Z };
С большой буквы наименование перечислений

2023-11-26 19:25 UTC, Gr871 commented on Assets/Scripts/Demonstration/InterpolationDemonstration.cs
> +    }
Пустые методы не нужны. Особенно Monobehaviour'овские

2023-11-26 19:25 UTC, Gr871 commented on Assets/Scripts/Demonstration/InterpolationDemonstration.cs
> +    [ContextMenu("Сферическая интерполяция")]
Супер, что зачинил кодировку, правда русский язык маскимум для комментариев оставь)))

2023-11-26 19:25 UTC, Gr871 commented on Assets/Scripts/Demonstration/InterpolationDemonstration.cs
> +    void Update()
не забывай ставить модификаторы, даже если Unity этого не делает. Здесь `private`

2023-11-26 19:26 UTC, Gr871 commented on Assets/Scripts/Demonstration/InterpolationDemonstration.cs
> +
Скобки поехали

2023-11-26 19:26 UTC, Gr871 commented on Assets/Scripts/Demonstration/InterpolationDemonstration.cs
> +
Выделение блоков посредством пустых строк - это хорошо, но не нужно ТАК сильно выделять)

2023-11-26 19:27 UTC, Gr871 commented on Assets/Scripts/Demonstration/Vector Demonstration.cs
>  {
открывающая фигурная скобка ВСЕГДА идет в одну линию с ОБЪЯВЛЕНИЕМ (класса, цикла, условия, ...)

2023-11-26 19:28 UTC, Gr871 commented on Assets/Scripts/CustomMath/Trigonometry.cs
> +}
Я так понимаю, задел на будущее?? но тут траблы:
1. Имя скрипта не соответствует имени класса
2. фигурная скобка открывающая не там стоит
3. а точно ли он нужен?

2023-11-26 19:28 UTC, Gr871 reviewed
Порешай эти моменты и заливай. В целом - отлично все!

2023-11-26 19:43 UTC, Gr871 approved these changes

2023-12-04 05:51 UTC, Gr871 requested changes

2023-12-04 05:51 UTC, Gr871 commented on Assets/Scripts/CustomMath/CubeRotation.cs
> +public class CubeRotation : MonoBehaviour
Так, ну, давай теперь результат в удобоваримый вид приведем:
1. Нужен ли этот класс вообще? используется ли он? если не используется - удали. Когда понадобится - тогда и добавишь. 

Если все-таки нужен, тогда

2023-12-04 05:51 UTC, Gr871 commented on Assets/Scripts/CustomMath/CubeRotation.cs
> +{
1. Открывающая скобка всегда идет в той же строек, что и объявление блока, который она открывает (в данном случае - класса)

Это же касается про функции ниже

2023-12-04 05:51 UTC, Gr871 commented on Assets/Scripts/CustomMath/CubeRotation.cs
> +    }
2. Если тебе не нужны функции (а пустые функции тебе не нужны - удаляй)

2023-12-04 05:51 UTC, Gr871 commented on Assets/Scripts/Demonstration/InterpolationDemonstration.cs
> +    //private CubeRotation CubeScript;
Здесь в основном пойдет речь об оставшемся мусоре: 

1. есть какой-то сакральный смысл в данном комментарии? думаю, что нет. Тогда убираем его

2023-12-04 05:51 UTC, Gr871 commented on Assets/Scripts/Demonstration/InterpolationDemonstration.cs
> +            //CubeScript.RotationCube(quaternionEuler);
Аналогично: нет никакого смысла хранить эти комментарии

2023-12-04 05:51 UTC, Gr871 commented on Assets/Scripts/Demonstration/InterpolationDemonstration.cs
> +    SLerpQuaternionFunk();
подчиненный блок текста всегда должен быть сдвинут ровно на 1 tab право. Сейчас у тебя объявление блока и его содержание находятся на одном уровне.

2023-12-04 05:51 UTC, Gr871 commented on Assets/Scripts/Demonstration/InterpolationDemonstration.cs
> +    //    Debug.Log(Interpolation.remap3D(0, 0, 2, 2, 2));
ненужный комментарий

2023-12-04 05:51 UTC, Gr871 commented on Assets/Scripts/Demonstration/InterpolationDemonstration.cs
> +    private void Start() {
Не нужная функция

2023-12-04 05:51 UTC, Gr871 commented on Assets/Scripts/Demonstration/InterpolationDemonstration.cs
>      private void OnDrawGizmos() {
Уже говорил, обращу внимание еще раз. Есть 2 функции:

`OnDrawGizmos` и `OnDrawGizomsSelected`. Различие в том, что первый рисует абсолютно всегда (отсюда у тебя нагромождение и смешение отрисованного, из которого ты пытаешься выкрутиться за счет включения/выключения флагов)
Второй рисует тогда, когда у тебя объект не то активен, не то выделен (точно не помню, скорее всего, когда он в иерархии выделен). 
Как ты можешь перестроить отрисовку:
1. Каждую маленькую задачу, которую требуется отрисовать, можно вынести в отдельный компонент.
2. Каждый такой компонент повесить на свой собственный объект (1 объект - 1 компонент, в котором происходит отрисовка)
3. Чтобы посмотреть отрисованное - тупо выделил сам объект с компонентом и балуешься. Надоел - выделил другой (ну или выключил, если для прочей гарантии)
4. Чтобы не получилось, что у тебя в корне лежит неразбираемая куча объектов, объедини их по урокам:

А. Урок "Rotation" - свой собственный объект (пустой, без компонентов). В нем подчиненные объекты 
1. Task 1 - объект, с компонентом, в котором решается задача "RotationFirstTask"
2. Task 2 - объект, с компонентом, в котором решается задача "RotationSecondTask"
3. и т.д.

2023-12-04 05:51 UTC, Gr871 commented on Assets/Scripts/Demonstration/InterpolationDemonstration.cs
>      private void OnDrawGizmos() {
Сейчас все это делить - не вижу смысла. Для будущих задач просто перенеси весь текущий код функций `OnDrawGizmos` в `OnDrawGizmosSelected`, чтобы можно было и код сохранить, и чтобы на сцене не мешал

2023-12-04 10:23 UTC, COBRA445 commented on Assets/Scripts/Demonstration/InterpolationDemonstration.cs
>      private void OnDrawGizmos() {
Да, я помню и понял этот момент, но мне не удалось его где либо применить, так как нужны объекты, а у меня их не было пока что) В следующий раз буду решать задачу придумывая как прикрутить объект.

2023-12-04 10:29 UTC, COBRA445 commented on Assets/Scripts/Demonstration/InterpolationDemonstration.cs
>      private void OnDrawGizmos() {
Не понял только, нужно ли мне сейчас мои функции переносить на объекты или нет?) Там же по сути интерполяция  - я и так точки рисую, нагромождать объектами не охото)

2023-12-05 06:25 UTC, Gr871 commented on Assets/Scripts/Demonstration/InterpolationDemonstration.cs
>      private void OnDrawGizmos() {
просто вот у тебя есть код в функции `OnDrawGizmos`
объяви рядом функции `OnDrawGizmosSelected`
и перенести содержимое функции `OnDrawGizmos` в `OnDrawGizmosSelected`

чтобы у тебя на сцене не захламлялась отрисовка по старым заданиям

2023-12-06 05:10 UTC, merged